import Head from 'next/head'
import Image from 'next/image'
import img1 from '@/imgs/img1.jpg'
import Hero from './Hero'




export default function Home() {
  return (
    <>
      <Head>
        <title>More's Art Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Hero />
        
      </main>
    </>
  )
}
